apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: microservices
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
spec:
  selector:
    matchLabels:
      app: microservices
  replicas: 5
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
      - name: microservices
        image: microservices
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000